<?php
/**
 * This file is auto-generated by BDE (Boring Database Engine) v0.1.0.
 * Do not edit this file directly.
 *
 * To regenerate this file, run:
 * bde generate
 *
 * @generated
 */
{% if namespace is defined and namespace is string and namespace != "" %}

namespace {{ namespace }};

{% endif %}
class {{ class_name }}
{
    {% for column in columns %}
    /**
     * @var {{ column.data_type.php_type.docblock_type }}
     */
    public {{ column.data_type.php_type.type_hint }} ${{ column.name }};
    {% endfor %}
}