<?php
/**
 * This file is auto-generated by BDE (Boring Database Engine) v0.1.0.
 * Do not edit this file directly.
 *
 * To regenerate this file, run:
 * bde generate
 *
 * @generated
 */

class Queries
{
    private \PDO $pdo;

    public function __construct(\PDO $pdo)
    {
        $this->pdo = $pdo;
}

{% for query in queries %}
{{ query }}
{% endfor %}
}