<?php
/**
 * This file is auto-generated by BDE (Boring Database Engine) v0.1.0.
 * Do not edit this file directly.
 *
 * To regenerate this file, run:
 * bde generate
 *
 * @generated
 */


namespace VendorName\Testing;


class Oauth
{
    
    /**
     * @var int
     */
    public int $id;
    
    /**
     * @var ?int
     */
    public ?int $user_id;
    
    /**
     * @var string
     */
    public string $provider;
    
    /**
     * @var string
     */
    public string $provider_user_id;
    
    /**
     * @var DateTime
     */
    public DateTime $created_at;
    
}