<?php
/**
 * This file is auto-generated by BDE (Boring Database Engine) v0.1.0.
 * Do not edit this file directly.
 *
 * To regenerate this file, run:
 * bde generate
 *
 * @generated
 */


namespace VendorName\Testing;


class Users
{
    
    /**
     * @var int
     */
    public int $id;
    
    /**
     * @var string
     */
    public string $username;
    
    /**
     * @var string
     */
    public string $email;
    
    /**
     * @var DateTime
     */
    public DateTime $created_at;
    
    /**
     * @var ?string
     */
    public ?string $name;
    
}